#!/bin/bash
# Environmental variables

# Add local binaries to PATH
export PATH=$PATH:/home/giosef/.local/bin

# Add path for arm gcc
export PATH=$PATH:/home/giosef/Documents/se_workdir/gcc-arm-none-eabi-10-2020-q4-major/bin

# Default terminal
export TERMINAL=alacritty
export TERM=alacritty
